import type { Metadata } from "next";
import { Geist, Geist_Mono, Antonio } from "next/font/google";

import "./globals.css";
import Navbar from "./sections/Navbar";
import Footer from "./sections/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const robotoMono = Geist_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
  style: "normal",
  fallback: ["system-ui", "sans-serif"],
  preload: true,
});

const antonio = Antonio({
  variable: "--font-antonio",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
  style: "normal",
  fallback: ["system-ui", "sans-serif"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en" className={`${geistSans.variable} ${robotoMono.variable} ${antonio.variable} ${geistMono.variable}`}>
      <head>
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
    <body>
      <Navbar />
      <div className="blue-bg min-h-screen">
        {children}
      </div>
      <Footer />
      </body>
    </html>
  );
}
